### PR TITLE
Add tanujshriyan

### LINKED ISSUE #272: add Tanujshriyan
#### How to get started
1) star :star: this repository (top right) so that you can keep up to date with recent contribution activity via [your github feed](https://github.com/)
2) follow the [README.md instructions](https://github.com/the-fast-tracked-programmer/close-my-first-issue)
#### If you get stuck and need some guidance or support
Jump into our discord channel [#community](https://discord.com/channels/815407176734212126/894788853045530624) and request help

### PR DESCRIPTION
**Pull request by Tanujshriyan**
closes #272

### CODE REVIEW

**Review by bedrock-adam — CHANGES_REQUESTED** [review]
Almost there @Tanujshriyan :smile: 

2 more steps:

1) update the pull request description to `closes #272` so that your issue will close automatically when the pull request is merged
2) re-request a review from us so we know when to take another look (top right)

Then we :+1: and :ship: this thing!

**Review by Tanujshriyan — COMMENTED** [review]
closes #272

**Review by guyandtheworld — CHANGES_REQUESTED** [review]
Hey, @Tanujshriyan great work adding these changes! Can you link the issue to this pull request so that it can be closed? You can do it by editing the text to have #<ISSUE NUMBER>

**Review by bedrock-adam — CHANGES_REQUESTED** [review]
Unfortunately github won't link an issue when referenced in a omment.

Will need to update the pull request description (e.g. see `closes #`)

**Review by bedrock-adam — APPROVED** [review]
Have updated the pull request description so we could get this one wrapped up for you @Tanujshriyan

great work on this :clap: :clap:

**Pull request merged**
