### PR TITLE
add rguptan.md  closes #194

### LINKED ISSUE #194: add rguptan
#### How to get started
1) star this repository (top right) so that you can keep an eye on what happens
2) follow the [README.md instructions](https://github.com/the-fast-tracked-programmer/close-my-first-issue)
#### If you get stuck and need some guidance or support
Jump into our discord channel [#community](https://discord.com/channels/815407176734212126/894788853045530624) and request help

### PR DESCRIPTION
**Pull request by rguptan**
closes #194

### CODE REVIEW

**Review by bedrock-adam — CHANGES_REQUESTED** [review]
Almost there @rguptan :smile: 

2 more steps:

1) update the pull request description to `closes #194` so that your issue will close automatically when the pull request is merged
2) re-request a review from us so we know when to take another look (top right)

Then we :+1: and :ship: this thing!

**Review by rguptan — COMMENTED** [review]
closes #194

**Comment by bedrock-adam** [comment]
doesn't work with a comment unfortunately, has to be the original pull request description. You can get to it by clicking the three dots `... -> edit` top right.

**Review by bedrock-adam — APPROVED** [review]
Nice one @rguptan!

**Pull request merged**
