### PR TITLE
LVictoria

### LINKED ISSUE #294: add LVictoria159753
#### How to get started
1) star :star: this repository (top right) so that you can keep up to date with recent contribution activity via [your github feed](https://github.com/)
2) follow the [README.md instructions](https://github.com/the-fast-tracked-programmer/close-my-first-issue)
#### If you get stuck and need some guidance or support
Jump into our discord channel [#community](https://discord.com/channels/815407176734212126/894788853045530624) and request help

### PR DESCRIPTION
**Pull request by LVictoria159753**
closes #294

### CODE REVIEW

**Comment by guyandtheworld** [comment]
Almost there @LVictoria159753  😄

2 more steps:

* can you remove the angle bracket (<>) so that the issue gets linked? eg. `closes #294`
* re-request a review from us so we know when to take another look (top right)
Then we 👍 and 🚢 this thing!

**Review by bedrock-adam — CHANGES_REQUESTED** [review]
Almost there @LVictoria159753 - see @guyandtheworld's comment :)

**Comment by LVictoria159753** [comment]
Hello Guyandtheworld as well as Bedrock-Adam,

Thank you so much for your comments! I just edited the angle bracket for the phrase, closes #294. I hope I did that right, but please let me know if there is anything else that I need to fix!

**Review by bedrock-adam — APPROVED** [review]
:tada:  great work on this @LVictoria159753 :tada:

let's get this thing shipped! :ship: :grin:

**Pull request merged**
